//only modify this file if a question or subquestion has to be changed
//otherwise DO NOT modify this file
const updateDataScript = [
  'UPDATE Question SET question = \'Was kannst Du richtig gut im Umgang mit anderen Menschen?\', subquestion = \'Zähle möglichst viel auf.\' WHERE question_number = \'2.1.1\'',
  'UPDATE Question SET question = \'Was fällt Dir manchmal schwer im Umgang mit anderen Menschen?\' WHERE question_number = \'2.2.1\'',
  'UPDATE Question SET question = \'Was möchtest Du in den nächsten Wochen ausprobieren?\', subquestion = \'Dies ist Teil Deines Veränderungsprojekts!\' WHERE question_number = \'2.3.1\'',
  'UPDATE Question SET question = \'Wer der Jugendlichen könnte Dir dabei helfen?\', subquestion = \'Wen willst Du einweihen und fragen, ob er/sie Dich unterstützt?\' WHERE question_number = \'2.5.1\'',
  'UPDATE Question SET question = \'Wer der Sozialpädagog*innen könnte Dir dabei helfen?\', subquestion = \'Die Sozialpädagog*innen in der WG sind ja dazu da, Dich zu unterstützen. Wen willst Du einbeziehen in Dein Veränderungsprojekt?\' WHERE question_number = \'2.5.2\'',
  'UPDATE Question SET question = \'Wer aus deiner Familie könnte Dir dabei helfen?\', subquestion = \'Wen willst Du einweihen und fragen, ob er/sie Dich unterstützt?\' WHERE question_number = \'2.5.3\'',
  'UPDATE Question SET question = \'Ein Gespräch anfangen/andere ansprechen\' WHERE question_number = \'3.2.1\'',
  'UPDATE Question SET question = \'In einer mir bekannten Gruppe etwas sagen/eine Idee vorbringen\' WHERE question_number = \'3.2.2\'',
  'UPDATE Question SET question = \'In einer mir unbekannten Gruppe etwas sagen/eine Idee vorbringen\' WHERE question_number = \'3.2.3\'',
  'UPDATE Question SET question = \'Etwas Lustiges sagen oder machen, andere zum Lachen bringen\' WHERE question_number = \'3.2.4\'',
  'UPDATE Question SET question = \'Jemanden anlächeln/einen Blick zuwerfen\' WHERE question_number = \'3.2.5\'',
  'UPDATE Question SET question = \'Jemanden neugierig machen/Interesse wecken\' WHERE question_number = \'3.2.6\'',
  'UPDATE Question SET question = \'Jemanden nach dem Befinden fragen\' WHERE question_number = \'3.3.1\'',
  'UPDATE Question SET question = \'Jemandem etwas Freundliches sagen/ein Kompliment machen\' WHERE question_number = \'3.3.2\'',
  'UPDATE Question SET question = \'Gut zuhören\' WHERE question_number = \'3.3.3\'',
  'UPDATE Question SET question = \'Jemandem etwas Wichtiges anvertrauen\' WHERE question_number = \'3.3.4\'',
  'UPDATE Question SET question = \'Gemeinsam lachen\' WHERE question_number = \'3.3.5\'',
  'UPDATE Question SET question = \'Auf eine Frage/ein Anliegen eingehen\' WHERE question_number = \'3.3.6\'',
  'UPDATE Question SET question = \'Eigene Irritationen/Schwierigkeiten ansprechen\' WHERE question_number = \'3.3.7\'',
  'UPDATE Question SET question = \'Freude über die Beziehung/das Gespräch zeigen\' WHERE question_number = \'3.4.1\'',
  'UPDATE Question SET question = \'Ansprechen, wie es weitergeht\' WHERE question_number = \'3.4.2\'',
  'UPDATE Question SET question = \'Jemandem ein Feedback geben \' WHERE question_number = \'3.4.3\'',
  'UPDATE Question SET question = \'Weitere Fragen formulieren\' WHERE question_number = \'3.4.4\'',
  'UPDATE Question SET question = \'Um ein weiteres Gespräch bitten\' WHERE question_number = \'3.4.5\'',
  'UPDATE Question SET question = \'Weitere Gesprächsmöglichkeiten ansprechen\' WHERE question_number = \'3.4.6\'',
];              