# This file is a template, and might need editing before it works on your project.
# https://hub.docker.com/r/google/dart
image: google/dart:2.8.4


variables:
  # Use to learn more:
  # pub run test --help
  PUB_VARS: "--platform vm --timeout 30s --concurrency=6 --test-randomize-ordering-seed=random --reporter=expanded"

  ANDROID_COMPILE_SDK: "30"
  #ANDROID_BUILD_TOOLS: "28.0.2"
  #ANDROID_SDK_TOOLS:   "4333796"

stages:
    - test
    - build

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .pub-cache/global_packages

before_script:
  - apt-get --quiet update --yes
  - export PATH="$PATH":"~/.pub-cache/bin"

debugTests:
  stage: test
  script:
    - flutter pub get
    - flutter packages pub run build_runner build
    - flutter test
    #- cd /builds/ip34-20bb/ip34-20bb_selfassessmentyouthapp/dateien
    #- dart --enable-asserts --enable-vm-service:59314 /builds/ip34-20bb/ip34-20bb_selfassessmentyouthapp/dateien/test/code_metrics_analyzer.dart
  artifacts:
    paths:
      - metrics/


assembleDebug:
  stage: build
  script:
    - flutter pub get
    - flutter packages pub run IP5_GitLab-Runner build
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/






