name: example
description: A new Flutter application.

author: Ketan Choyal <ketanchoyal@gmail.com>
homepage: https://github.com/ketanchoyal/custom_radio_grouped_button

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  custom_radio_grouped_button:
    path: ../

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
